# Generated by Django 4.2.6 on 2023-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField()),
                ('Country', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('Hobbies', models.CharField(max_length=100)),
                ('Upload_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
